version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/my-app/src:/app/my-app/src  # Ensures local changes are reflected in the container
